<?php

declare(strict_types=1);

require_once __DIR__ . '/npc_generator.php';

function rg_get_encounter_options(): array
{
    return [
        'categories' => ['monster', 'animal'],
    ];
}

function rg_get_bestiary(): array
{
    return [
        'monster' => [
            [
                'name' => 'Abyss Worm',
                'strength' => 10, 'agility' => 2,
                'skills' => 'Melee 4',
                'movement' => 1,
                'weapon' => 'Bite', 'damage' => 3, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 1,
                'special' => 'Burrows underground; charges from below without warning.',
                'hook' => 'The ground trembles and splits before the worm erupts beneath you.',
            ],
            [
                'name' => 'Bloodling',
                'strength' => 5, 'agility' => 6,
                'skills' => 'Melee 4, Move 3',
                'movement' => 2,
                'weapon' => 'Claws', 'damage' => 2, 'damage_type' => 'Slash',
                'count_min' => 2, 'count_max' => 6,
                'special' => 'Feeds on blood; heals 1 HP for each wound it inflicts.',
                'hook' => 'Pale, silent shapes emerge from the mist, drawn by the scent of blood.',
            ],
            [
                'name' => 'Demon',
                'strength' => 8, 'agility' => 6,
                'skills' => 'Melee 5, Move 3',
                'movement' => 2,
                'weapon' => 'Hellfire Strike', 'damage' => 3, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 2,
                'special' => 'Immune to non-magical weapons. Causes fear on first sight.',
                'hook' => 'A rift tears open the air; the smell of sulfur fills the clearing.',
            ],
            [
                'name' => 'Death Knight',
                'strength' => 9, 'agility' => 5,
                'skills' => 'Melee 6, Endurance 4',
                'movement' => 1,
                'weapon' => 'Sword', 'damage' => 2, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 1,
                'special' => 'Aura of dread. Raises fallen enemies as undead at end of combat.',
                'hook' => 'A knight in black, rusted armor stands motionless on the road ahead.',
            ],
            [
                'name' => 'Dragon',
                'strength' => 14, 'agility' => 6,
                'skills' => 'Melee 6, Move 3, Scout 5',
                'movement' => 2,
                'weapon' => 'Claws & Bite', 'damage' => 4, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 1,
                'special' => 'Fire breath (Area, Damage 3). Armored scales reduce all damage by 2.',
                'hook' => 'A shadow blots out the sun; the distant roar shakes the treetops.',
            ],
            [
                'name' => 'Drakewyrm',
                'strength' => 11, 'agility' => 5,
                'skills' => 'Melee 5, Move 3',
                'movement' => 2,
                'weapon' => 'Bite', 'damage' => 3, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 2,
                'special' => 'Acid spit attack at range. Corrodes armor over time.',
                'hook' => 'Scorched trees and melted rock mark the trail of the beast.',
            ],
            [
                'name' => 'Ent',
                'strength' => 12, 'agility' => 1,
                'skills' => 'Melee 4, Endurance 5',
                'movement' => 1,
                'weapon' => 'Slam', 'damage' => 3, 'damage_type' => 'Blunt',
                'count_min' => 1, 'count_max' => 1,
                'special' => 'Immune to blunt damage. Vulnerable to fire.',
                'hook' => 'An ancient oak shifts; two massive eyes open among the bark.',
            ],
            [
                'name' => 'Ghost',
                'strength' => 2, 'agility' => 8,
                'skills' => 'Move 5, Stealth 4',
                'movement' => 3,
                'weapon' => 'Ethereal Touch', 'damage' => 2, 'damage_type' => 'Blunt',
                'count_min' => 1, 'count_max' => 3,
                'special' => 'Can only be harmed by silver, magic, or blessed weapons. Passes through walls.',
                'hook' => 'Candles extinguish one by one as a chill fills the air.',
            ],
            [
                'name' => 'Giant',
                'strength' => 13, 'agility' => 2,
                'skills' => 'Melee 5, Endurance 4',
                'movement' => 1,
                'weapon' => 'Club', 'damage' => 4, 'damage_type' => 'Blunt',
                'count_min' => 1, 'count_max' => 1,
                'special' => 'Can throw boulders as a ranged attack (Damage 3).',
                'hook' => 'Footsteps like thunder precede the colossal figure cresting the hill.',
            ],
            [
                'name' => 'Giant Squid',
                'strength' => 11, 'agility' => 4,
                'skills' => 'Melee 4, Move 3',
                'movement' => 2,
                'weapon' => 'Tentacles', 'damage' => 2, 'damage_type' => 'Blunt',
                'count_min' => 1, 'count_max' => 1,
                'special' => 'Can grapple up to 3 targets at once. Ink cloud blocks sight.',
                'hook' => 'The water darkens and churns; something immense rises beneath the boat.',
            ],
            [
                'name' => 'Gray Bear',
                'strength' => 8, 'agility' => 3,
                'skills' => 'Melee 4, Scout 3',
                'movement' => 1,
                'weapon' => 'Claws', 'damage' => 2, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 2,
                'special' => 'Enraged when wounded; gains +2 to Melee while below half HP.',
                'hook' => 'A heavy musk fills the forest, followed by a low, resonant growl.',
            ],
            [
                'name' => 'Gryphon',
                'strength' => 8, 'agility' => 7,
                'skills' => 'Melee 4, Move 5, Scout 4',
                'movement' => 3,
                'weapon' => 'Talons', 'damage' => 2, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 2,
                'special' => 'Swooping dive attack deals double damage on first strike.',
                'hook' => 'A shriek from above; a golden shape dives from the clouds.',
            ],
            [
                'name' => 'Harpies',
                'strength' => 4, 'agility' => 8,
                'skills' => 'Move 6, Melee 3, Scout 5',
                'movement' => 3,
                'weapon' => 'Talons', 'damage' => 1, 'damage_type' => 'Slash',
                'count_min' => 3, 'count_max' => 8,
                'special' => 'Shrieking song causes confusion; targets must test Wits or lose their action.',
                'hook' => 'Mocking screams echo from above as winged shapes begin to circle.',
            ],
            [
                'name' => 'Hydra',
                'strength' => 12, 'agility' => 3,
                'skills' => 'Melee 6, Endurance 5',
                'movement' => 1,
                'weapon' => 'Bite (multiple)', 'damage' => 3, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 1,
                'special' => 'Each head can attack independently. Severed heads regrow unless cauterized.',
                'hook' => 'The marsh explodes as a tangle of serpentine necks surges from the water.',
            ],
            [
                'name' => 'Insectoid Workers & Drones',
                'strength' => 5, 'agility' => 3,
                'skills' => 'Melee 2, Scout 2',
                'movement' => 1,
                'weapon' => 'Bite', 'damage' => 1, 'damage_type' => 'Slash',
                'count_min' => 6, 'count_max' => 16,
                'special' => 'Armor Rating 4. Swarm: when 4+ attack the same target, gain +1 to Melee rolls.',
                'hook' => 'A clicking sound rises from the tall grass before the swarm bursts forward.',
            ],
            [
                'name' => 'Insectoid Soldiers',
                'strength' => 7, 'agility' => 4,
                'skills' => 'Melee 4, Scout 3',
                'movement' => 2,
                'weapon' => 'Bite', 'damage' => 2, 'damage_type' => 'Slash',
                'count_min' => 2, 'count_max' => 8,
                'special' => 'Armor Rating 4. Bite injects paralyzing poison (Potency 7; target loses next action on failure).',
                'hook' => 'Larger, armored shapes push through the workers — the colony is defending something.',
            ],
            [
                'name' => 'Insectoid Queen',
                'strength' => 14, 'agility' => 3,
                'skills' => 'Melee 5, Endurance 6',
                'movement' => 1,
                'weapon' => 'Bite', 'damage' => 2, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 1,
                'special' => 'Armor Rating 6. Bite injects lethal poison (Potency 8; victim dies in D6 rounds on failure). Surrounded by D6+4 Soldiers at all times.',
                'hook' => 'The tunnel opens into a vast chamber pulsing with larvae — the Queen rises from the center.',
            ],
            [
                'name' => 'Manticore',
                'strength' => 9, 'agility' => 6,
                'skills' => 'Melee 5, Move 4, Scout 3',
                'movement' => 2,
                'weapon' => 'Claws & Tail', 'damage' => 2, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 1,
                'special' => 'Tail spike volley (ranged, 3 spikes, Damage 1 each). Can attack front and rear simultaneously.',
                'hook' => 'A human-like face grins atop a lion\'s body; the barbed tail arcs overhead.',
            ],
            [
                'name' => 'Minotaur',
                'strength' => 10, 'agility' => 3,
                'skills' => 'Melee 6, Endurance 4',
                'movement' => 1,
                'weapon' => 'Axe', 'damage' => 3, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 2,
                'special' => 'Charge attack: if it moves before striking, damage is doubled.',
                'hook' => 'Heavy hooves strike stone in the dark; the beast snorts and charges.',
            ],
            [
                'name' => 'Nightwargs',
                'strength' => 6, 'agility' => 7,
                'skills' => 'Move 5, Melee 4, Scout 6',
                'movement' => 3,
                'weapon' => 'Bite', 'damage' => 2, 'damage_type' => 'Slash',
                'count_min' => 2, 'count_max' => 6,
                'special' => 'Shadow camouflage in darkness; -2 to detect them at night.',
                'hook' => 'Amber eyes glow between the trees before the pack surges out of the dark.',
            ],
            [
                'name' => 'Sea Serpent',
                'strength' => 12, 'agility' => 4,
                'skills' => 'Melee 5, Move 3',
                'movement' => 2,
                'weapon' => 'Bite', 'damage' => 3, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 1,
                'special' => 'Can capsize small vessels. Tail sweep attacks all adjacent targets.',
                'hook' => 'The sea boils and a colossal neck rises, circling the hull slowly.',
            ],
            [
                'name' => 'Strangling Vine',
                'strength' => 7, 'agility' => 1,
                'skills' => 'Melee 3, Endurance 5',
                'movement' => 0,
                'weapon' => 'Vines', 'damage' => 2, 'damage_type' => 'Blunt',
                'count_min' => 1, 'count_max' => 3,
                'special' => 'Grapples on hit; grappled targets lose movement. Immune to Slash damage.',
                'hook' => 'The undergrowth shifts and tightens; a vine whips forward with purpose.',
            ],
            [
                'name' => 'Troll',
                'strength' => 11, 'agility' => 3,
                'skills' => 'Melee 5, Endurance 6',
                'movement' => 1,
                'weapon' => 'Fists', 'damage' => 3, 'damage_type' => 'Blunt',
                'count_min' => 1, 'count_max' => 2,
                'special' => 'Regenerates 2 HP per round. Regeneration stops only if damaged by fire or acid.',
                'hook' => 'The bridge keeper demands a toll; its grin shows far too many teeth.',
            ],
            [
                'name' => 'Restless Dead',
                'strength' => 3, 'agility' => 2,
                'skills' => 'Melee 2, Scout 2',
                'movement' => 1,
                'weapon' => 'Bite', 'damage' => 2, 'damage_type' => 'Slash',
                'count_min' => 2, 'count_max' => 8,
                'special' => 'Immune to fear, poison, and disease. Driven by an unfinished purpose in life.',
                'hook' => 'Pale hands claw upward from the earth; the graveyard stirs at midnight.',
            ],
            [
                'name' => 'Skeleton',
                'strength' => 3, 'agility' => 2,
                'skills' => 'Melee 3, Scout 3',
                'movement' => 1,
                'weapon' => 'Rusty Broadsword', 'damage' => 2, 'damage_type' => 'Slash',
                'count_min' => 2, 'count_max' => 10,
                'special' => 'BONY: Arrows and pointed weapons deal at most 1 damage. Wears studded leather or chainmail and a closed helmet.',
                'hook' => 'Hollow eye sockets glow faint blue as the rattling warriors rise from the dungeon floor.',
            ],
            [
                'name' => 'Ghoul',
                'strength' => 4, 'agility' => 2,
                'skills' => 'Melee 3, Scout 3',
                'movement' => 1,
                'weapon' => 'Bite', 'damage' => 2, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 5,
                'special' => 'Bite has Virulence 4 — victim must pass Endurance or become paralyzed for D6 rounds.',
                'hook' => 'The stench of rot fills the crypt before the hunched shapes drag themselves into the torchlight.',
            ],
            [
                'name' => 'Wyvern',
                'strength' => 10, 'agility' => 6,
                'skills' => 'Melee 5, Move 4, Scout 4',
                'movement' => 2,
                'weapon' => 'Stinger', 'damage' => 3, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 1,
                'special' => 'Stinger injects poison (Strength test or suffer -2 to all rolls for D6 rounds).',
                'hook' => 'Leathery wings beat overhead; the barbed tail seeks its target.',
            ],
        ],
        'animal' => [
            [
                'name' => 'Bear',
                'strength' => 6, 'agility' => 2,
                'skills' => 'Melee 3, Scout 3',
                'movement' => 1,
                'weapon' => 'Paw', 'damage' => 2, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 2,
                'special' => 'Maul: on a push, the bear pins its target (Strength test to break free).',
                'hook' => 'A bear with cubs blocks the mountain path and will not yield.',
            ],
            [
                'name' => 'Wolf',
                'strength' => 4, 'agility' => 4,
                'skills' => 'Move 3, Melee 3, Scout 5',
                'movement' => 2,
                'weapon' => 'Bite', 'damage' => 1, 'damage_type' => 'Slash',
                'count_min' => 3, 'count_max' => 8,
                'special' => 'Pack hunters: +1 damage per additional wolf attacking the same target.',
                'hook' => 'Howls echo from three directions; the pack is coordinating.',
            ],
            [
                'name' => 'Fox',
                'strength' => 2, 'agility' => 4,
                'skills' => 'Move 2, Melee 2, Scout 4',
                'movement' => 1,
                'weapon' => 'Bite', 'damage' => 1, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 2,
                'special' => 'Rarely aggressive; only attacks when cornered or protecting a den.',
                'hook' => 'A clever fox has been raiding camp supplies and leads pursuers into a trap.',
            ],
            [
                'name' => 'Deer',
                'strength' => 3, 'agility' => 4,
                'skills' => 'Move 4, Scout 4',
                'movement' => 2,
                'weapon' => 'Horns', 'damage' => 1, 'damage_type' => 'Blunt',
                'count_min' => 1, 'count_max' => 4,
                'special' => 'Flees on sight; only fights if cornered or during rut season.',
                'hook' => 'A magnificent stag stands in the clearing, seemingly unafraid.',
            ],
            [
                'name' => 'Boar',
                'strength' => 4, 'agility' => 2,
                'skills' => 'Melee 3, Scout 3',
                'movement' => 1,
                'weapon' => 'Tusks', 'damage' => 1, 'damage_type' => 'Blunt',
                'count_min' => 1, 'count_max' => 3,
                'special' => 'Charge: moves up to 2 hexes before striking for +1 damage.',
                'hook' => 'A wounded boar crashes out of the undergrowth, enraged and bleeding.',
            ],
            [
                'name' => 'Riding Horse',
                'strength' => 5, 'agility' => 4,
                'skills' => 'Move 2, Scout 3',
                'movement' => 2,
                'weapon' => 'Kick', 'damage' => 1, 'damage_type' => 'Blunt',
                'count_min' => 1, 'count_max' => 4,
                'special' => 'Bolts when frightened; rider must pass Agility test to stay mounted.',
                'hook' => 'A riderless horse wanders the road, still saddled and trembling.',
            ],
            [
                'name' => 'War Horse',
                'strength' => 6, 'agility' => 5,
                'skills' => 'Move 3, Melee 2, Scout 3',
                'movement' => 2,
                'weapon' => 'Kick', 'damage' => 1, 'damage_type' => 'Blunt',
                'count_min' => 1, 'count_max' => 2,
                'special' => 'Trained for combat; does not flee from melee and can be directed to trample.',
                'hook' => 'A war horse bearing a fallen knight gallops toward the party at full speed.',
            ],
            [
                'name' => 'Donkey',
                'strength' => 3, 'agility' => 3,
                'skills' => 'Move 2, Endurance 2, Scout 3',
                'movement' => 2,
                'weapon' => 'Kick', 'damage' => 1, 'damage_type' => 'Blunt',
                'count_min' => 1, 'count_max' => 3,
                'special' => 'Stubborn; refuses to move when overloaded or frightened unless led by hand.',
                'hook' => 'A loaded donkey stands alone at a crossroads with no owner in sight.',
            ],
            [
                'name' => 'Canide War Hound',
                'strength' => 5, 'agility' => 3,
                'skills' => 'Move 2, Melee 3, Scout 3',
                'movement' => 2,
                'weapon' => 'Bite', 'damage' => 1, 'damage_type' => 'Slash',
                'count_min' => 2, 'count_max' => 4,
                'special' => 'Trained to hold; bite grapples the limb (-1 Movement until freed).',
                'hook' => 'Guard dogs patrol the perimeter; their handler is nowhere to be seen.',
            ],
            [
                'name' => 'Crocodile',
                'strength' => 4, 'agility' => 2,
                'skills' => 'Melee 3, Scout 3',
                'movement' => 1,
                'weapon' => 'Bite', 'damage' => 2, 'damage_type' => 'Slash',
                'count_min' => 1, 'count_max' => 3,
                'special' => 'Death roll: on a hit, target is dragged underwater (Strength test to resist).',
                'hook' => 'The river bank looks safe until the mud shifts and lunges.',
            ],
        ],
    ];
}

function rg_generate_encounter(array $options = []): array
{
    $encounterOptions = rg_get_encounter_options();
    $bestiary = rg_get_bestiary();

    $selectedCategory = isset($options['category']) && is_string($options['category'])
        ? rg_filter_value(trim($options['category']), $encounterOptions['categories'])
        : null;

    $category = $selectedCategory ?? rg_pick($encounterOptions['categories']);

    $pool = $bestiary[$category];
    $creature = rg_pick($pool);

    $count = random_int($creature['count_min'], $creature['count_max']);

    $terrains = [
        'Dense forest with low visibility.',
        'Open plains under a grey sky.',
        'Rocky canyon with narrow passages.',
        'Shallow marshland with fog.',
        'Abandoned village at night.',
        'Underground cave network.',
        'Coastal cliffs above crashing waves.',
        'A frozen river crossing.',
        'Thick undergrowth at dusk.',
        'Ruined fortress courtyard.',
    ];

    $times = ['at dawn', 'at midday', 'at dusk', 'in the dead of night', 'during a rainstorm', 'under a full moon'];

    $countLabel = $count === 1
        ? '1 ' . $creature['name']
        : $count . 'x ' . $creature['name'];

    return [
        'name'        => $creature['name'],
        'category'    => ucfirst($category),
        'count'       => $countLabel,
        'strength'    => (string)$creature['strength'],
        'agility'     => (string)$creature['agility'],
        'skills'      => $creature['skills'],
        'movement'    => (string)$creature['movement'],
        'weapon'      => $creature['weapon'],
        'damage'      => (string)$creature['damage'],
        'damage_type' => $creature['damage_type'],
        'special'     => $creature['special'],
        'terrain'     => rg_pick($terrains),
        'time'        => rg_pick($times),
        'hook'        => $creature['hook'],
    ];
}
